name: Build and Push Docker Image Staging
"on":
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true
  push:
    branches:
      - release/*
      - hotfix/*
      - develop

jobs:
  build_and_deploy_stage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            fetch-tags: true

      - name: Set commit sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract version from branch name (for release branches)
        if: startsWith(steps.extract_branch.outputs.branch, 'release/')
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(steps.extract_branch.outputs.branch, 'hotfix/')
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
          VERSION=${BRANCH_NAME#hotfix/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for develop branche)
        if: startsWith(steps.extract_branch.outputs.branch, 'develop')
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
          VERSION=$(git describe --tags --always)
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from input (for manual workflow dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - name: get build time
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>${GITHUB_ENV}

      - name: Get api docs artifacts
        env:
          GH_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: |
          gh run download -R green-ecolution/backend -n api-docs.json 
          mv api-docs.json ./backend-client/api-docs.json

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VITE_APP_VERSION="${{env.RELEASE_VERSION}}-stage"
            VITE_APP_GIT_COMMIT=${{env.COMMIT_SHA}}
            VITE_APP_GIT_BRANCH=${{steps.extract_branch.outputs.branch}}
            VITE_APP_BUILD_TIME=${{env.BUILD_TIME}}
            VITE_APP_GIT_REPOSITORY=${{github.repository}}
          file: ./.docker/Dockerfile.stage
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:${{ env.RELEASE_VERSION }}-stage,ghcr.io/${{ env.REPO_LC }}:${{ env.COMMIT_SHA }}-stage

      - name: Notify management repo to update submodules
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          repository: green-ecolution/green-ecolution
          event-type: "update-submodules-stage"
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ env.COMMIT_SHA }}", "version": "${{ env.RELEASE_VERSION }}", "from": "frontend"}'

