name: 'Build and test project on PR'

on:
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  build_and_test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Get api docs artifacts
        env:
          GH_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: |
          gh run download -R green-ecolution/backend -n api-docs.json 
          mv api-docs.json ./backend-client/api-docs.json

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          yarn ci

      - name: Build
        run: |
          yarn build

      - name: Linter
        continue-on-error: false
        run: |
          yarn lint

      - name: Test
        run: |
          yarn test
